spring:
  datasource:
    hikari:
      username: STSBOOT
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:ORCL
      password: '7777'
  
  jpa:
    generate-ddl: 'false'
    database: oracle
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.OracleDialect
  
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: '5050'

mybatis:
  configuration:
    map-underscore-to-camel-case: 'true'
